name: build-and-release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - name: 安装 Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - name: 下载 upx
        run: |
          Invoke-WebRequest -Uri "https://github.com/upx/upx/releases/download/v4.2.1/upx-4.2.1-win64.zip" -OutFile "upx.zip"
          Expand-Archive upx.zip -DestinationPath .
      - name: 构建 release
        run: cargo build --release
      - name: upx 压缩
        run: .\upx-4.2.1-win64\upx.exe --best --lzma target\release\epub_emoji_x.exe
      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: epub_emoji_x.exe
          path: target/release/epub_emoji_x.exe
      - name: 发布 Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: target/release/epub_emoji_x.exe
